#!/usr/bin/env bash
set -euo pipefail

# lo-github-sync.sh — Reconcile GitHub automation to match PROJECT.md status
# Usage: lo-github-sync.sh [--fix] [--no-build]

FIX=false
NO_BUILD=false
for arg in "$@"; do
  case "$arg" in
    --fix) FIX=true ;;
    --no-build) NO_BUILD=true ;;
    *) echo "Unknown argument: $arg"; echo "Usage: lo-github-sync.sh [--fix] [--no-build]"; exit 1 ;;
  esac
done

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m'

ok()      { echo -e "  ${GREEN}ok${NC}       $1"; }
fixed()   { echo -e "  ${CYAN}fixed${NC}    $1"; }
skipped() { echo -e "  ${YELLOW}skipped${NC}  $1"; }
dryrun()  { echo -e "  ${YELLOW}dryrun${NC}  $1"; }
err()     { echo -e "  ${RED}error${NC}    $1"; }

# ── State Detection ──────────────────────────────────────────────────

if [[ ! -f ".lo/PROJECT.md" ]]; then
  echo "No .lo/PROJECT.md found. Run /lo:new first."
  exit 1
fi

STATUS=$(grep -m1 '^status:' .lo/PROJECT.md | sed 's/status:[[:space:]]*"\{0,1\}\([^"]*\)"\{0,1\}/\1/' | sed 's/#.*//' | tr '[:upper:]' '[:lower:]' | xargs)
if [[ -z "$STATUS" ]]; then
  echo "Could not parse status from .lo/PROJECT.md"
  exit 1
fi

ACTIVE=false
if [[ "$STATUS" == "build" || "$STATUS" == "open" ]]; then
  ACTIVE=true
fi

REMOTE=""
OWNER=""
REPO=""
HAS_REMOTE=false
if git remote get-url origin &>/dev/null; then
  REMOTE=$(git remote get-url origin)
  OWNER_REPO=$(echo "$REMOTE" | sed -E 's#.*github\.com[:/]([^/]+/[^/.]+)(\.git)?$#\1#')
  OWNER=$(echo "$OWNER_REPO" | cut -d/ -f1)
  REPO=$(echo "$OWNER_REPO" | cut -d/ -f2)
  HAS_REMOTE=true
fi

HAS_TEST=false
HAS_BUILD=false
if [[ -f "package.json" ]]; then
  # Check for script keys directly — don't try to parse JSON block boundaries
  if grep -q '"test"[[:space:]]*:' package.json; then HAS_TEST=true; fi
  if grep -q '"build"[[:space:]]*:' package.json; then HAS_BUILD=true; fi
fi

if [[ "$NO_BUILD" == "true" ]]; then HAS_BUILD=false; fi

SUPABASE_URL=""
# Only extract publishable (anon) keys — never service_role or secret keys.
# Publishable keys are safe to commit; they're public by design.
SUPABASE_KEY=""
for envfile in .env.example .env.template .env.local.example env.d.ts; do
  if [[ -f "$envfile" ]]; then
    URL_MATCH=$(grep -oE 'https://[a-z0-9]+\.supabase\.co' "$envfile" 2>/dev/null | head -1 || true)
    KEY_MATCH=$(grep -oE 'sb_publishable_[A-Za-z0-9_-]+' "$envfile" 2>/dev/null | head -1 || true)
    if [[ -n "$URL_MATCH" && -z "$SUPABASE_URL" ]]; then SUPABASE_URL="$URL_MATCH"; fi
    if [[ -n "$KEY_MATCH" && -z "$SUPABASE_KEY" ]]; then SUPABASE_KEY="$KEY_MATCH"; fi
  fi
done

CI_MANAGED=false
CI_EXISTS=false
CI_JOB_NAME=""

get_ci_metadata() {
  CI_MANAGED=false
  CI_EXISTS=false
  CI_JOB_NAME=""
  if [[ -f ".github/workflows/ci.yml" ]]; then
    CI_EXISTS=true
    if grep -q 'looselyorganized/ci/.github/workflows/reusable-ci.yml' .github/workflows/ci.yml; then
      CI_MANAGED=true
      CI_JOB_NAME=$(grep -E '^\s+\w+:' .github/workflows/ci.yml | grep -B1 'uses:' | head -1 | sed 's/[: ]//g' || echo "ci")
    else
      CI_JOB_NAME="custom"
    fi
  fi
}

get_ci_metadata

echo ""
echo "lo-github-sync: ${OWNER}/${REPO} (status: ${STATUS}, active: ${ACTIVE})"
if [[ "$FIX" == "false" ]]; then
  echo -e "${YELLOW}DRY RUN — pass --fix to apply changes${NC}"
fi
echo ""

# ── .coderabbit.yaml Reconciliation ─────────────────────────────────

reconcile_coderabbit() {
  local TARGET_ENABLED="false"
  if [[ "$ACTIVE" == "true" ]]; then TARGET_ENABLED="true"; fi

  local TARGET_CONTENT="# Auto-generated by lo-github-sync — do not edit manually
reviews:
  auto_review:
    enabled: ${TARGET_ENABLED}"

  if [[ -f ".coderabbit.yaml" ]]; then
    CURRENT=$(cat .coderabbit.yaml)
    if [[ "$CURRENT" == "$TARGET_CONTENT" ]]; then
      ok ".coderabbit.yaml          reviews.auto_review.enabled: ${TARGET_ENABLED}"
      return
    fi
  fi

  if [[ "$FIX" == "true" ]]; then
    echo "$TARGET_CONTENT" > .coderabbit.yaml
    fixed ".coderabbit.yaml          reviews.auto_review.enabled: ${TARGET_ENABLED}"
  else
    dryrun ".coderabbit.yaml          reviews.auto_review.enabled: ${TARGET_ENABLED}"
  fi
}

reconcile_coderabbit

# ── CI Workflow Reconciliation ───────────────────────────────────────

reconcile_ci() {
  if [[ "$CI_EXISTS" == "true" && "$CI_MANAGED" == "false" ]]; then
    ok ".github/workflows/ci.yml   custom (not managed)"
    return
  fi

  local TARGET=""
  if [[ "$ACTIVE" == "true" ]]; then
    TARGET="# Auto-generated by lo-github-sync — do not edit manually
name: CI
on:
  pull_request:
    branches: [main]
jobs:
  pipeline:
    uses: looselyorganized/ci/.github/workflows/reusable-ci.yml@main
    with:
      status: ${STATUS}"
    if [[ "$HAS_TEST" == "true" ]]; then TARGET="${TARGET}
      has-test: true"; fi
    if [[ "$HAS_BUILD" == "true" ]]; then TARGET="${TARGET}
      has-build: true"; fi
    if [[ -n "$SUPABASE_URL" ]]; then TARGET="${TARGET}
      supabase-url: ${SUPABASE_URL}"; fi
    if [[ -n "$SUPABASE_KEY" ]]; then TARGET="${TARGET}
      supabase-key: ${SUPABASE_KEY}"; fi

    local DESC="${STATUS}"
    local CAPS=""
    [[ "$HAS_TEST" == "true" ]] && CAPS="${CAPS}, test"
    [[ "$HAS_BUILD" == "true" ]] && CAPS="${CAPS}, build"
    [[ -n "$CAPS" ]] && DESC="${DESC} (${CAPS#, })"
  else
    TARGET="# Auto-generated by lo-github-sync — do not edit manually
name: CI
on:
  pull_request:
    branches: [main]
jobs:
  pipeline:
    uses: looselyorganized/ci/.github/workflows/reusable-ci.yml@main
    with:
      status: ${STATUS}"
    local DESC="${STATUS} (dormant)"
  fi

  if [[ "$CI_EXISTS" == "true" ]]; then
    CURRENT=$(cat .github/workflows/ci.yml)
    if [[ "$CURRENT" == "$TARGET" ]]; then
      ok ".github/workflows/ci.yml   ${DESC}"
      return
    fi
  fi

  if [[ "$FIX" == "true" ]]; then
    mkdir -p .github/workflows
    echo "$TARGET" > .github/workflows/ci.yml
    fixed ".github/workflows/ci.yml   ${DESC}"
  else
    dryrun ".github/workflows/ci.yml   ${DESC}"
  fi
}

reconcile_ci

# ── Auto-merge Workflow Reconciliation ───────────────────────────────

reconcile_auto_merge_workflow() {
  local TARGET_CONTENT='# Auto-generated by lo-github-sync — do not edit manually
name: Auto-merge
on:
  pull_request:
    types: [opened]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge (squash)
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
          REPO: ${{ github.repository }}
        run: gh pr merge "$PR_NUMBER" --auto --squash --repo "$REPO"'

  if [[ "$ACTIVE" == "true" ]]; then
    if [[ -f ".github/workflows/auto-merge.yml" ]]; then
      CURRENT=$(cat .github/workflows/auto-merge.yml)
      if [[ "$CURRENT" == "$TARGET_CONTENT" ]]; then
        ok "auto-merge.yml             present"
        return
      fi
    fi
    if [[ "$FIX" == "true" ]]; then
      mkdir -p .github/workflows
      echo "$TARGET_CONTENT" > .github/workflows/auto-merge.yml
      fixed "auto-merge.yml             present"
    else
      dryrun "auto-merge.yml             needs creation"
    fi
  else
    if [[ -f ".github/workflows/auto-merge.yml" ]]; then
      if [[ "$FIX" == "true" ]]; then
        rm .github/workflows/auto-merge.yml
        fixed "auto-merge.yml             removed"
      else
        dryrun "auto-merge.yml             needs removal"
      fi
    else
      ok "auto-merge.yml             absent"
    fi
  fi
}

reconcile_auto_merge_workflow

# ── Scheduled Audit Workflow Reconciliation ──────────────────────────

reconcile_scheduled_audit() {
  local TARGET_CONTENT='# Auto-generated by lo-github-sync — do not edit manually
name: Scheduled Audit
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('"'"'bun.lock'"'"') }}
          restore-keys: bun-${{ runner.os }}-
      - run: bun install
      - run: npm audit --audit-level=critical'

  if [[ "$STATUS" == "open" && -f "package.json" ]]; then
    if [[ -f ".github/workflows/audit.yml" ]]; then
      CURRENT=$(cat .github/workflows/audit.yml)
      if [[ "$CURRENT" == "$TARGET_CONTENT" ]]; then
        ok "audit.yml                   weekly scheduled"
        return
      fi
    fi
    if [[ "$FIX" == "true" ]]; then
      mkdir -p .github/workflows
      echo "$TARGET_CONTENT" > .github/workflows/audit.yml
      fixed "audit.yml                   weekly scheduled"
    else
      dryrun "audit.yml                   needs creation"
    fi
  else
    if [[ -f ".github/workflows/audit.yml" ]]; then
      if [[ "$FIX" == "true" ]]; then
        rm .github/workflows/audit.yml
        fixed "audit.yml                   removed"
      else
        dryrun "audit.yml                   needs removal"
      fi
    else
      ok "audit.yml                   absent"
    fi
  fi
}

reconcile_scheduled_audit

# ── GitHub API: Auto-merge Setting ───────────────────────────────────

reconcile_auto_merge_setting() {
  if [[ "$HAS_REMOTE" == "false" ]]; then
    skipped "Auto-merge setting         no remote"
    return
  fi

  local CURRENT
  CURRENT=$(gh api "repos/${OWNER}/${REPO}" --jq '.allow_auto_merge' 2>/dev/null || echo "unknown")

  if [[ "$ACTIVE" == "true" ]]; then
    if [[ "$CURRENT" == "true" ]]; then
      ok "Auto-merge setting         enabled"
      return
    fi
    if [[ "$FIX" == "true" ]]; then
      gh api "repos/${OWNER}/${REPO}" --method PATCH \
        --input - <<< '{"allow_auto_merge": true}' >/dev/null 2>&1 \
        && fixed "Auto-merge setting         enabled" \
        || err "Auto-merge setting         failed to enable"
    else
      dryrun "Auto-merge setting         needs enabling"
    fi
  else
    if [[ "$CURRENT" == "false" ]]; then
      ok "Auto-merge setting         disabled"
      return
    fi
    if [[ "$FIX" == "true" ]]; then
      gh api "repos/${OWNER}/${REPO}" --method PATCH \
        --input - <<< '{"allow_auto_merge": false}' >/dev/null 2>&1 \
        && fixed "Auto-merge setting         disabled" \
        || err "Auto-merge setting         failed to disable"
    else
      dryrun "Auto-merge setting         needs disabling"
    fi
  fi
}

reconcile_auto_merge_setting

# ── GitHub API: Branch Protection ────────────────────────────────────

# Refresh CI metadata — reconcile_ci may have created/rewritten ci.yml
get_ci_metadata

reconcile_branch_protection() {
  if [[ "$HAS_REMOTE" == "false" ]]; then
    skipped "Branch protection          no remote"
    return
  fi

  local CURRENT_STATUS
  CURRENT_STATUS=$(gh api "repos/${OWNER}/${REPO}/branches/main/protection" --jq '.required_pull_request_reviews.required_approving_review_count' 2>&1) || CURRENT_STATUS="none"
  # If gh returned error JSON instead of a number, treat as none
  if [[ ! "$CURRENT_STATUS" =~ ^[0-9]+$ ]]; then CURRENT_STATUS="none"; fi

  if [[ "$ACTIVE" == "true" ]]; then
    local CHECKS="[]"
    local CHECK_DESC="1 reviewer"

    local CHECKS_ARRAY=()

    if [[ "$CI_EXISTS" == "true" ]]; then
      if [[ "$CI_MANAGED" == "true" ]]; then
        local JOB=$CI_JOB_NAME
        [[ -z "$JOB" ]] && JOB="pipeline"
        CHECKS_ARRAY+=("{\"context\": \"${JOB} / Gate\"}")
        [[ "$HAS_TEST" == "true" ]] && CHECKS_ARRAY+=("{\"context\": \"${JOB} / Unit Tests\"}")
        [[ "$HAS_BUILD" == "true" ]] && CHECKS_ARRAY+=("{\"context\": \"${JOB} / Build\"}")
      else
        while IFS= read -r job_name; do
          [[ -n "$job_name" ]] && CHECKS_ARRAY+=("{\"context\": \"${job_name}\"}")
        done < <(awk '/^jobs:/{found=1; next} found && /^[[:space:]]+[A-Za-z0-9_-]+:/{name=$1; sub(/:$/,"",name); print name; count++; if(count>=5) exit} found && /^[^[:space:]]/{exit}' .github/workflows/ci.yml)
      fi

      if [[ ${#CHECKS_ARRAY[@]} -gt 0 ]]; then
        CHECKS=$(printf '%s,' "${CHECKS_ARRAY[@]}")
        CHECKS="[${CHECKS%,}]"
        CHECK_DESC="1 reviewer + checks"
      fi
    fi

    if [[ "$CURRENT_STATUS" == "1" ]]; then
      # Verify check names match, not just reviewer count
      local CURRENT_CHECKS
      CURRENT_CHECKS=$(gh api "repos/${OWNER}/${REPO}/branches/main/protection/required_status_checks" --jq '[.checks[].context] | sort | join(",")' 2>&1) || CURRENT_CHECKS=""
      # If gh returned error JSON, treat as no checks
      if [[ "$CURRENT_CHECKS" == *"message"* ]]; then CURRENT_CHECKS=""; fi
      local EXPECTED_CHECKS=""
      if [[ ${#CHECKS_ARRAY[@]} -gt 0 ]]; then
        # Extract context values, sort, join
        EXPECTED_CHECKS=$(printf '%s\n' "${CHECKS_ARRAY[@]}" | sed 's/.*"context": "\([^"]*\)".*/\1/' | sort | paste -sd ',' -)
      fi
      if [[ "$CURRENT_CHECKS" == "$EXPECTED_CHECKS" ]]; then
        ok "Branch protection          ${CHECK_DESC}"
        return
      fi
    fi

    if [[ "$FIX" == "true" ]]; then
      local PAYLOAD
      if [[ "$CHECKS" == "[]" ]]; then
        PAYLOAD='{
          "required_status_checks": null,
          "enforce_admins": false,
          "required_pull_request_reviews": {
            "required_approving_review_count": 1
          },
          "restrictions": null
        }'
      else
        PAYLOAD="{
          \"required_status_checks\": {
            \"strict\": true,
            \"checks\": ${CHECKS}
          },
          \"enforce_admins\": false,
          \"required_pull_request_reviews\": {
            \"required_approving_review_count\": 1
          },
          \"restrictions\": null
        }"
      fi

      gh api "repos/${OWNER}/${REPO}/branches/main/protection" \
        --method PUT \
        --input - <<< "$PAYLOAD" >/dev/null 2>&1 \
        && fixed "Branch protection          ${CHECK_DESC}" \
        || err "Branch protection          failed (may need Team plan)"
    else
      dryrun "Branch protection          ${CHECK_DESC}"
    fi
  else
    if [[ "$CURRENT_STATUS" == "none" ]]; then
      ok "Branch protection          none"
      return
    fi
    if [[ "$FIX" == "true" ]]; then
      local DEL_STATUS
      DEL_STATUS=$(gh api "repos/${OWNER}/${REPO}/branches/main/protection" --method DELETE 2>&1 && echo "ok" || echo "failed")
      if [[ "$DEL_STATUS" == *"ok"* || "$DEL_STATUS" == *"404"* || "$DEL_STATUS" == *"not protected"* ]]; then
        fixed "Branch protection          removed"
      else
        err "Branch protection          failed to remove"
      fi
    else
      dryrun "Branch protection          needs removal"
    fi
  fi
}

reconcile_branch_protection
